---
- name: Install postfix
  ansible.builtin.apt:
    name:
    - postfix
    - postfix-ldap

- name: Set Postfix config
  ansible.builtin.template:
    src: postfix.main.cf
    dest: /etc/postfix/main.cf